/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Industrial Tech-Sleek Themes
        cream: {
          50: '#FDFDF8',   // Main background
          100: '#F8F7F2',
          200: '#EEEFE9',  // Section gray
        },
        taupe: {
          100: '#E8E4D9',
          200: '#E0DCCE',  // Navbar color
          300: '#D4CFC0',
          400: '#C5BFAE',
        },
        // Theme-aware accent aliases (light: #EB9D2A, dark: #FFBC66 via --c-primary)
        amber: {
          DEFAULT: 'rgb(var(--c-primary) / <alpha-value>)',
          primary: 'rgb(var(--c-primary) / <alpha-value>)',
          shadow: 'oklch(var(--c-shadow-amber) / <alpha-value>)',
          border: 'oklch(var(--c-border-amber) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'rgb(var(--c-on-surface) / <alpha-value>)',
          light: 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
          muted: 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        },
        surface: 'rgb(var(--c-surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--c-surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--c-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
        'surface-warm': 'rgb(var(--c-surface-warm) / <alpha-value>)',
        'surface-raised': 'rgb(var(--c-surface-raised) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--c-surface-elevated) / <alpha-value>)',
        'surface-section': 'rgb(var(--c-surface-section) / <alpha-value>)',
        'surface-navbar': 'rgb(var(--c-surface-navbar) / <alpha-value>)',
        background: 'rgb(var(--c-background) / <alpha-value>)',
        'on-background': 'rgb(var(--c-on-background) / <alpha-value>)',
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        outline: 'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
        primary: 'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
        'on-primary-strong': 'rgb(var(--c-on-primary-strong) / <alpha-value>)',
        'primary-container': 'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--c-on-primary) / <alpha-value>)',
        'inverse-primary': '#FFB95E',
        secondary: '#6366F1',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#6063EE',
        'on-secondary-container': '#FFFBFF',
        tertiary: '#00658C',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#3CB8F3',
        'on-tertiary-container': '#004662',
        'electric-purple': '#6366F1',
        'glowing-orange': 'rgb(var(--c-primary) / <alpha-value>)',
        'cosmic-void': 'rgb(var(--c-cosmic-void) / <alpha-value>)',
        'success-green': 'oklch(var(--c-accent-green) / <alpha-value>)',
        'accent-green': 'oklch(var(--c-accent-green) / <alpha-value>)',
        'accent-green-container': 'oklch(var(--c-accent-green-container) / <alpha-value>)',
        'accent-blue': 'oklch(var(--c-accent-blue) / <alpha-value>)',
        'accent-purple': 'oklch(var(--c-accent-purple) / <alpha-value>)',
        'shadow-amber': 'oklch(var(--c-shadow-amber) / <alpha-value>)',
        'border-amber': 'oklch(var(--c-border-amber) / <alpha-value>)',
        pinterest: '#E60023',
        'status-pin': 'oklch(var(--c-status-pin) / <alpha-value>)',
        'status-match': 'oklch(var(--c-status-match) / <alpha-value>)',
        'muted-text': 'rgb(var(--c-text-muted) / <alpha-value>)',
        'text-muted': 'rgb(var(--c-text-muted) / <alpha-value>)',
        'warm-cream': 'rgb(var(--c-warm-cream) / <alpha-value>)',
        'warm-white': 'rgb(var(--c-warm-white) / <alpha-value>)',
        void: 'rgb(var(--c-void) / <alpha-value>)'
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'display-hero': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'display-hero-mobile': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'headline-section': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'headline-card': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'body-large': ['"DM Sans"', 'system-ui', 'sans-serif'],
        'body-ui': ['"DM Sans"', 'system-ui', 'sans-serif'],
        'label-button': ['"DM Sans"', 'system-ui', 'sans-serif'],
        'label-eyebrow': ['"DM Sans"', 'system-ui', 'sans-serif'],
        'label-micro': ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['84px', { lineHeight: '1', fontWeight: '700' }],
        'display-hero-mobile': ['48px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-section': ['52px', { lineHeight: '1.1', fontWeight: '600' }],
        'headline-card': ['26px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-large': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-ui': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-button': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'label-eyebrow': ['11px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.15em' }],
        'label-micro': ['10px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      spacing: {
        'max-width': '1180px',
        'margin-desktop': '52px',
        'margin-mobile': '20px',
        'gutter': '24px',
        'section-v': '104px',
        unit: '8px',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '3rem',
      },
      boxShadow: {
        'btn-primary': '0 2px 0 0 oklch(var(--c-shadow-amber))',
        'btn-secondary': '0 2px 0 0 rgb(var(--c-primary))',
        'btn-primary-hover': '0 4px 0 0 oklch(var(--c-shadow-amber))',
        'btn-secondary-hover': '0 4px 0 0 rgb(var(--c-primary))',
        'editorial-card': '0 14px 40px rgba(20, 18, 32, 0.08)',
        'glass-soft': '0 10px 30px rgba(20, 18, 32, 0.07)',
        'hero-cta': 'var(--shadow-hero-cta)',
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
